FROM microsoft/windowsservercore:1709
USER ContainerAdministrator
EXPOSE 8080
ADD ./consume-memory/consume-memory.exe ./consume-memory/consume-memory.exe
ADD ./consume-cpu/consume-cpu.exe ./consume-cpu/consume-cpu.exe
ADD resource-consumer.exe resource-consumer
ENTRYPOINT ["/resource-consumer"]
