apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- path: patches/cluster.yaml
- target:
    group: bootstrap.cluster.x-k8s.io
    version: v1beta1
    kind: KubeadmConfigTemplate
    name: .*-md-win
    namespace: default
  path: patches/kubeadm-windows.yaml
