apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: runhcs-wcow-hypervisor
handler: runhcs-wcow-hypervisor
scheduling:
  nodeSelector:
    kubernetes.io/os: 'windows'
    kubernetes.io/arch: 'amd64'
  tolerations:
  - effect: NoSchedule
    key: os
    operator: Equal 
    value: "windows"