apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  annotations:
    runtime: containerd
  name: ${CLUSTER_NAME}-md-win
  namespace: default
spec:
  template:
    spec:
      image:
        computeGallery:
          gallery: wcctpub-85c68f48-bd4b-40ad-99b7-4a2faaadf526
          name: yuanliangtest
          version: 0.3.1748735262
