apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  annotations:
    runtime: containerd
  name: ${CLUSTER_NAME}-md-win
  namespace: default
spec:
  template:
    spec:
      image:
        computeGallery:
          gallery: wcctpub-151cac41-04fa-4bf3-b811-419553465c10
          name: yuanliangtest
          version: 0.3.1747617671
