apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  annotations:
    runtime: containerd
  name: ${CLUSTER_NAME}-md-win
  namespace: default
spec:
  template:
    spec:
      image:
        computeGallery:
          subscriptionID: "${AZURE_SUBSCRIPTION_ID:=46678f10-4bbb-447e-98e8-d2829589f2d8}"
          resourceGroup: "${AZURE_RESOURCE_GROUP:=cluster-api-gallery}"
          gallery: "${GALLERY_NAME:=community_gallery}"
          name: "${GALLERY_IMAGE_NAME:=capi-win-2022-containerd}"
          version: "${IMAGE_VERSION:=latest}"
