# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: hyperv-webhook-build

on:
  push:
    branches:
      - main
      - master
    paths:
      - helpers/hyperv-mutating-webhook/**
  pull_request:
    branches:
      - main
      - master
    paths:
      - helpers/hyperv-mutating-webhook/**
  workflow_dispatch: # for testing until workfload is validated

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build image for ci
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cd helpers/hyperv-mutating-webhook
          make docker-build
      - name: build image for release
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "${{ secrets.DOCKER_SECRET }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          make docker-push
